### ISSUE TITLE
How to use this with gulp?

### ISSUE THREAD

**Issue by slorber** [caspervonb/amok#3]
Hi,

I have a gulp pipeline, my app is not build by a simple bundler command line.
The builded app is split into "app.js" for things that changes often, and "appLib.js" for libs. 
Only "app.js" needs to be hot reloaded.

On build watchify or browserify, these 2 files are build or updated in "build/app.js" and "build/appLib.js"
After starting chrome in debug mode on port 6666, I tried:

```
sebastien@sebastien-xps:build (dev $)$ amok "app.js" -p 12345 -P 6666
Server listening on http://127.0.0.1:12345

/home/sebastien/Desktop/devhome/install/node-v0.10.24-linux-x64/lib/node_modules/amok/node_modules/rdbg/index.js:57
    var socket = ws.connect(target.webSocketDebuggerUrl);
                                  ^
TypeError: Cannot read property 'webSocketDebuggerUrl' of undefined
    at DebugClient.attach (/home/sebastien/Desktop/devhome/install/node-v0.10.24-linux-x64/lib/node_modules/amok/node_modules/rdbg/index.js:57:35)
    at DebugClient.<anonymous> (/home/sebastien/Desktop/devhome/install/node-v0.10.24-linux-x64/lib/node_modules/amok/index.js:92:12)
    at DebugClient.g (events.js:180:16)
    at DebugClient.EventEmitter.emit (events.js:95:17)
    at /home/sebastien/Desktop/devhome/install/node-v0.10.24-linux-x64/lib/node_modules/amok/node_modules/rdbg/index.js:25:14
    at IncomingMessage.<anonymous> (/home/sebastien/Desktop/devhome/install/node-v0.10.24-linux-x64/lib/node_modules/amok/node_modules/rdbg/index.js:46:9)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

Is this how it is supposed to be used?

**Comment by slorber** [comment]
Hmmm I just got no stacktrace using default debugger port:

```
sebastien@sebastien-xps:build (dev $)$ amok "app.js" -p 12345
Server listening on http://127.0.0.1:12345
Debugger attached to http://localhost:9000/
```

**Comment by caspervonb** [comment]
@slorber Since processing is optional, you can let your gulp process do the building, and give it the expected output files instead.

```sh
amok build/app.js build/lib.js --no-bundler
```

```js
TypeError: Cannot read property 'webSocketDebuggerUrl' of undefined
```

This would be because chrome is not listening on the port you specified, I think I'll be changing this to be a warning instead of a failure

```js
url.js:107
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
```
Bug, I'll get that fixed this coming weekend.

**Comment by slorber** [comment]
thanks tell me when it's fixed plz :)

**Comment by caspervonb** [comment]
Fixed in 0.1.x

**Comment by slorber** [comment]
Hi,

Errors are gone but it still does not work for me.

First it seems that it succeed to attach the chrome debugger only the first time.

```
sebastien@sebastien-xps:Stample-react (dev *$%)$ amok build/app.js --no-bundler
Attaching debugger...
Server listening on http://127.0.0.1:9966
Debugger attached to http://localhost:9000/
```

Then restarting amok seems to not attach the debugger.

```
amok build/app.js --no-bundler
Attaching debugger...
Server listening on http://127.0.0.1:9966
```

To be able to reattach it seems to require to restart Chrome.

---------------------

Once the debugger is successfully attached, I try to modify my files so that `build/app.js` is updated by gulp/browserify. But it seems to not hot reload and produce an error log:

```
sebastien@sebastien-xps:Stample-react (dev *$%)$ amok build/app.js --no-bundler
Attaching debugger...
Server listening on http://127.0.0.1:9966
Debugger attached to http://localhost:9000/
Unknown script build/app.js
```

**Comment by caspervonb** [comment]
Unknown script is usually the result of script collection, e.g if there are no references in your script used, for example, the following is a one shot script

```js
console.log('foo');
```

There is nothing to re-compile in that script, it has already been evaluated and thrown away, in contrast

```js
setInterval(function() {
  console.log('foo');
}, 1000);
```
Will not be collected, at least until clearInterval is called.

Makes sense?

**Comment by slorber** [comment]
Hmmm I'm not really sure to understand what this means.

The app.js file is pretty big and is my main app bundle containing all my app code.
It does not contain setInterval (at its entry point), just app initialization code.

```
function initialize(bootData) {
   console.debug("starting app");
   ...
}

// This is the entry point of the app, exposed thanks to a browserify "external require"
// See http://stackoverflow.com/questions/25269359/inject-data-in-a-browserify-app
exports.start = function(bootData) {
    $(function() {
        try {
            initialize(bootData);
        } catch (e) {
            console.error("Can't initialize stample app");
            console.error(e.stack);
        }
    });
};
```

You maybe mean that on reload the start() method is never called so reloading my `app.js` just does nothing?

**Comment by caspervonb** [comment]
The snippet you posted, looks like it would be a one shot run and throw away kind of a thing. We do code recompilation, so there is evaluation of things that have already happened in the past, those have happened and in terms of the VM are thrown away for good.

Example
```js
// this application, has nothing that could be re-compiled, it will be run once and there is no behavior to change.
console.log('hello world');
```

```js
// this is persistent, thus is suitable for live modification.
setInterval(function() {
  console.log('hello world');
}, 1000);
```

**Comment by nmn** [comment]
SOO Close.

So i have no errors now. 

I'm using this command:
```
amok public/js/app.js --no-bundler --port 8000
```

At the same time I have my own build script running and compiling app.js. And a node server listening on port 8000.

I get the website to open correctly, but I do not get any live updates at all. :(

What am I doing wrong?

**Comment by caspervonb** [comment]
@nmn Try running this https://gist.github.com/caspervonb/d58c3eecb72ba3dd0846, let me know how that goes.

**Comment by caspervonb** [comment]
@nmn turns out, I broke the file watchers, it should be fixed in 0.5
